apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: loggings.capabilities.morningspace.io
spec:
  compositeTypeRef:
    apiVersion: capabilities.morningspace.io/v1alpha1
    kind: Logging
  resources:
  - base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: operator.ibm.com/v1alpha1
            kind: OperandConfig
            metadata: {}
            spec:
              services:
              - name: elastic-cloud-eck
                spec:
                  elasticsearch:
                    nodeSets:
                    - name: default
                      count: 1
                      config:
                        node.store.allow_mmap: false
                  kibana:
                    count: 1
                    elasticsearchRef:
                      name: elasticsearch-sample
    patches:
    - fromFieldPath: metadata.annotations[capabilities.morningspace.io/provider-config]
      toFieldPath: spec.providerConfigRef.name
    - fromFieldPath: metadata.name
      toFieldPath: metadata.name
      transforms:
      - type: string
        string:
          fmt: 'opcon-%s'
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.manifest.metadata.name
      transforms:
      - type: string
        string:
          fmt: '%s'
    - fromFieldPath: spec.claimRef.namespace
      toFieldPath: spec.forProvider.manifest.metadata.namespace
    - fromFieldPath: spec.esVersion
      toFieldPath: spec.forProvider.manifest.spec.services[0].spec.elasticsearch.version
    - fromFieldPath: spec.kibanaVersion
      toFieldPath: spec.forProvider.manifest.spec.services[0].spec.kibana.version
    readinessChecks:
    - type: None
  - base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: operator.ibm.com/v1alpha1
            kind: OperandRegistry
            metadata: {}
            spec:
              operators:
              - name: elastic-cloud-eck
                channel: stable
                packageName: elastic-cloud-eck
                scope: public
                sourceName: operatorhubio-catalog
                sourceNamespace: olm
    patches:
    - fromFieldPath: metadata.annotations[capabilities.morningspace.io/provider-config]
      toFieldPath: spec.providerConfigRef.name
    - fromFieldPath: metadata.name
      toFieldPath: metadata.name
      transforms:
      - type: string
        string:
          fmt: 'opreg-%s'
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.manifest.metadata.name
      transforms:
      - type: string
        string:
          fmt: '%s'
    - fromFieldPath: spec.claimRef.namespace
      toFieldPath: spec.forProvider.manifest.metadata.namespace
    - fromFieldPath: spec.claimRef.namespace
      toFieldPath: spec.forProvider.manifest.spec.operators[0].namespace
    readinessChecks:
    - type: None
  - base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: operator.ibm.com/v1alpha1
            kind: OperandRequest
            metadata: {}
            spec:
              requests:
              - operands:
                - name: elastic-cloud-eck
    patches:
    - fromFieldPath: metadata.annotations[capabilities.morningspace.io/provider-config]
      toFieldPath: spec.providerConfigRef.name
    - fromFieldPath: metadata.name
      toFieldPath: metadata.name
      transforms:
      - type: string
        string:
          fmt: 'opreq-%s'
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.manifest.metadata.name
      transforms:
      - type: string
        string:
          fmt: '%s'
    - fromFieldPath: spec.claimRef.namespace
      toFieldPath: spec.forProvider.manifest.metadata.namespace
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.manifest.spec.requests[0].registry
      transforms:
      - type: string
        string:
          fmt: '%s'
    - fromFieldPath: spec.claimRef.namespace
      toFieldPath: spec.forProvider.manifest.spec.requests[0].registryNamespace
    readinessChecks:
    - type: MatchString
      fieldPath: status.atProvider.manifest.status.phase
      matchString: Running