---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capabilities-shim-resources
rules:
- apiGroups:
  - kubernetes.crossplane.io
  resources:
  - objects
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: capabilities-shim-resources
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: capabilities-shim-resources
subjects:
- kind: ServiceAccount
  namespace: crossplane-system
  name: crossplane