apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: loggings.capabilities.morningspace.io
spec:
  compositeTypeRef:
    apiVersion: capabilities.morningspace.io/v1alpha1
    kind: Logging
  resources:
  - base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              namespace: operators
            spec:
              channel: stable
              name: elastic-cloud-eck
              source: operatorhubio-catalog
              sourceNamespace: olm
    patches:
    - fromFieldPath: metadata.annotations[capabilities.morningspace.io/provider-config]
      toFieldPath: spec.providerConfigRef.name
    - fromFieldPath: metadata.name
      toFieldPath: metadata.name
      transforms:
      - type: string
        string:
          fmt: 'sub-%s'
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.manifest.metadata.name
      transforms:
      - type: string
        string:
          fmt: '%s'
    readinessChecks:
    - fieldPath: status.atProvider.manifest.status.installedCSV
      type: NonEmpty
  - base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: elasticsearch.k8s.elastic.co/v1
            kind: Elasticsearch
            metadata: {}
            spec:
              nodeSets:
              - name: default
                count: 1
                config:
                  node.store.allow_mmap: false
    patches:
    - fromFieldPath: metadata.annotations[capabilities.morningspace.io/provider-config]
      toFieldPath: spec.providerConfigRef.name
    - fromFieldPath: metadata.name
      toFieldPath: metadata.name
      transforms:
      - type: string
        string:
          fmt: 'elasticsearch-%s'
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.manifest.metadata.name
      transforms:
      - type: string
        string:
          fmt: '%s'
    - fromFieldPath: spec.claimRef.namespace
      toFieldPath: spec.forProvider.manifest.metadata.namespace
    - fromFieldPath: spec.esVersion
      toFieldPath: spec.forProvider.manifest.spec.version
    readinessChecks:
    - type: MatchString
      fieldPath: status.atProvider.manifest.status.phase
      matchString: "Ready"
    - type: MatchString
      fieldPath: status.atProvider.manifest.status.health
      matchString: "green"
  - base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: kibana.k8s.elastic.co/v1
            kind: Kibana
            metadata: {}
            spec:
              count: 1
    patches:
    - fromFieldPath: metadata.annotations[capabilities.morningspace.io/provider-config]
      toFieldPath: spec.providerConfigRef.name
    - fromFieldPath: metadata.name
      toFieldPath: metadata.name
      transforms:
      - type: string
        string:
          fmt: 'kibana-%s'
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.manifest.metadata.name
      transforms:
      - type: string
        string:
          fmt: '%s'
    - fromFieldPath: spec.claimRef.namespace
      toFieldPath: spec.forProvider.manifest.metadata.namespace
    - fromFieldPath: spec.kibanaVersion
      toFieldPath: spec.forProvider.manifest.spec.version
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.manifest.spec.elasticsearchRef.name
      transforms:
      - type: string
        string:
          fmt: '%s'
    readinessChecks:
    - type: MatchString
      fieldPath: status.atProvider.manifest.status.associationStatus
      matchString: "Established"
    - type: MatchString
      fieldPath: status.atProvider.manifest.status.health
      matchString: "green"
