apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: networkings.capabilities.olm.morningspace.io
  labels:
    capability: networking
    provider: olm
spec:
  compositeTypeRef:
    apiVersion: capabilities.morningspace.io/v1alpha1
    kind: Networking
  resources:
  - base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              namespace: operators
            spec:
              channel: alpha
              name: kong
              source: operatorhubio-catalog
              sourceNamespace: olm
    patches:
    - fromFieldPath: metadata.annotations[capabilities.morningspace.io/provider-config]
      toFieldPath: spec.providerConfigRef.name
    - fromFieldPath: metadata.name
      transforms:
      - type: string
        string:
          fmt: 'sub-%s'
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.manifest.metadata.name
    readinessChecks:
    - type: NonEmpty
      fieldPath: status.atProvider.manifest.status.currentCSV
  - base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      metadata:
        annotations:
          kubernetes.crossplane.io/managementType: "observable_and_deletable"
      spec:
        dependencies:
        - fromObject:
            apiVersion: kubernetes.crossplane.io/v1alpha1
            kind: Object
            fieldPath: status.atProvider.manifest.status.currentCSV
          toFieldPath: spec.forProvider.manifest.metadata.name
        forProvider:
          manifest:
            apiVersion: operators.coreos.com/v1alpha1
            kind: ClusterServiceVersion
            metadata:
              namespace: operators
    patches:
    - fromFieldPath: metadata.annotations[capabilities.morningspace.io/provider-config]
      toFieldPath: spec.providerConfigRef.name
    - fromFieldPath: metadata.name
      transforms:
      - type: string
        string:
          fmt: 'csv-%s'
    - fromFieldPath: metadata.name
      toFieldPath: spec.dependencies[0].fromObject.name
      transforms:
      - type: string
        string:
          fmt: 'sub-%s'
    readinessChecks:
    - type: MatchString
      fieldPath: status.atProvider.manifest.status.phase
      matchString: Succeeded
  - base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        dependencies:
        - fromObject:
            apiVersion: kubernetes.crossplane.io/v1alpha1
            kind: Object
            fieldPath: status.atProvider.manifest.status.phase
        forProvider:
          manifest:
            apiVersion: charts.helm.k8s.io/v1alpha1
            kind: Kong
            metadata:
              namespace: default
            spec:
              proxy:
                type: NodePort
              env:
                prefix: /kong_prefix/
              resources:
                limits:
                  cpu: 500m
                  memory: 512Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
              ingressController:
                enabled: true
                installCRDs: false
    patches:
    - fromFieldPath: metadata.annotations[capabilities.morningspace.io/provider-config]
      toFieldPath: spec.providerConfigRef.name
    - fromFieldPath: metadata.name
      transforms:
      - type: string
        string:
          fmt: 'kong-%s'
    - fromFieldPath: metadata.name
      toFieldPath: spec.dependencies[0].fromObject.name
      transforms:
      - type: string
        string:
          fmt: 'csv-%s'
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.manifest.metadata.name
    - fromFieldPath: spec.claimRef.namespace
      toFieldPath: spec.forProvider.manifest.metadata.namespace
    - fromFieldPath: spec.parameters.proxyType
      toFieldPath: spec.forProvider.manifest.spec.proxy.type
    - fromFieldPath: spec.parameters.resources.limits.cpu
      toFieldPath: spec.forProvider.manifest.spec.resources.limits.cpu
    - fromFieldPath: spec.parameters.resources.limits.memory
      toFieldPath: spec.forProvider.manifest.spec.resources.limits.memory
    - fromFieldPath: spec.parameters.resources.requests.cpu
      toFieldPath: spec.forProvider.manifest.spec.resources.requests.cpu
    - fromFieldPath: spec.parameters.resources.requests.memory
      toFieldPath: spec.forProvider.manifest.spec.resources.requests.memory
    readinessChecks:
    - fieldPath: status.atProvider.manifest.status.deployedRelease
      type: NonEmpty
