---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: olm-capabilities-shim-resources
  namespace: operators
rules:
- apiGroups:
  - operators.coreos.com
  resources:
  - subscriptions
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: olm-capabilities-shim-resources
  namespace: operators
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: olm-capabilities-shim-resources
subjects:
- kind: ServiceAccount
  namespace: crossplane-system
  name: crossplane