apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: networkings.capabilities.morningspace.io
spec:
  group: capabilities.morningspace.io
  names:
    kind: Networking
    plural: networkings
  claimNames:
    kind: NetworkingClaim
    plural: networkingclaims
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              proxyType:
                description: The proxy type
                type: string
              resources:
                description: The resource declaration
                type: object
                properties:
                  limits:
                    type: object
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                  requests:
                    type: object
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
