---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: networking-capabilities-shim-resources
rules:
- apiGroups:
  - charts.helm.k8s.io
  resources:
  - kongs
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: networking-capabilities-shim-resources
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: networking-capabilities-shim-resources
subjects:
- kind: ServiceAccount
  namespace: crossplane-system
  name: crossplane
