apiVersion: capabilities.morningspace.io/v1alpha1
kind: LoggingClaim
metadata:
  annotations:
    # capabilities.morningspace.io/operator-namespace: operators
    capabilities.morningspace.io/provider-config: kubernetes-provider
  name: my-logging-stack
  namespace: default
spec:
  esVersion: 7.13.3
  kibanaVersion: 7.13.3
  compositionSelector:
    matchLabels:
      capability: logging
      provider: olm
